
//  ----------------------------------------------- AUTH -----------------------------------------------
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'


export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const USER_PROFILE_LOADED_SUCCES = "USER_PROFILE_LOADED_SUCCES"
export const USER_PROFILE_LOADED_FAIL = "USER_PROFILE_LOADED_FAIL"

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'
export const LOGGOUT = "LOGGOUT"

export const PASSWORD_RESET_SUCCESS ="PASSWORD_RESET_SUCCESS"
export const PASSWORD_RESET_FAIL  = 'PASSWORD_RESET_FAIL'

export const PASSWORD_RESET_CONFIRM_SUCCESS ="PASSWORD_RESET_CONFIRM_SUCCESS"
export const PASSWORD_RESET_CONFIRM_FAIL  = 'PASSWORD_RESET_CONFIRM_FAIL'


// For Future Implemenation
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';




//  ----------------------------------------------- POLLS -----------------------------------------------
export const POLLS_LOADED_SUCCESS = 'POLLS_LOADED_SUCCESS'
export const POLLS_LOADED_FAIL = 'POLLS_LOADED_FAIL'


export const POLL_LOADED_SUCCESS = "POLL_LOADED_SUCCESS"
export const POLL_LOADED_FAIL = "POLL_LOADED_FAIL"

